Error & Style fix on recent visitors
Error: recentVisitors.php used to show the first 5 entries in the database instead of the desired last 5 entries
This was fixed by changing the order by to DESC instead of ASC

Style: Made the entries more readable by splitting the sql result up into a html table